# permissions for end users to edit podinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podinfo-editor-role
rules:
- apiGroups:
  - flux.fluxdev.io
  resources:
  - podinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.fluxdev.io
  resources:
  - podinfoes/status
  verbs:
  - get
